services:
  main-service:
    build: ./main-service
    container_name: mainContainer
    ports:
      - "80:80"
  cart-service:
    build: ./cart-service
    container_name: cartContainer
    ports:
      - "81:80"
  order-service:
    build: ./order-service
    container_name: orderContainer
    ports:
      - "82:80"
  product-service:
    build: ./product-service
    container_name: productContainer
    ports:
      - "83:80"
  user-service:
    build: ./user-service
    container_name: userContainer
    ports:
      - "84:80"
